In [18]:
# Esercizio passeggiata aleatoria su un grafo

In [19]:
# k_1 = 3, k_2 = 3, k_3 = 3, k_4 = 3, k_5 = 4
# Matrice di transizione
# p_11 = 0, p_12 = 1/3, p_13 = 0, p_14 = 1/3, p_15 = 1/3
# p_21 = 1/3, p_22 = 0, p_23 = 1/3, p_24 = 0, p_25 = 1/3
# p_31 = 0, p_32 = 1/3, p_33 = 0, p_34 = 1/3, p_35 = 1/3
# p_41 = 1/3, p_42 = 0, p_43 = 1/3, p_44 = 0, p_45 = 1/3
# p_51 = 1/4, p_52 = 1/4, p_53 = 1/4, p_54 = 1/4, p_55 = 0
#
# Distribuzione stazionaria
# k = 3+3+3+3+4 = 16
# v_1 = v_2 = v_3 = v_4 = 3/16, v_5 = 4/16 = 1/4

In [20]:
import numpy as np

In [21]:
P = np.array([[0, 1/3, 0, 1/3, 1/3],[1/3, 0, 1/3, 0, 1/3],[0, 1/3, 0, 1/3, 1/3],
             [1/3, 0, 1/3, 0, 1/3], [1/4, 1/4, 1/4, 1/4, 0]])
display(P)

array([[0.        , 0.33333333, 0.        , 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.33333333, 0.        , 0.33333333],
       [0.        , 0.33333333, 0.        , 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.33333333, 0.        , 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.        ]])

In [22]:
# Metodo analitico

In [23]:
lam, V = np.linalg.eig(P.T)
display(lam)
display(V)

array([ 1.00000000e+00+0.00000000e+00j, -6.66666667e-01+0.00000000e+00j,
       -3.33333333e-01+0.00000000e+00j,  1.28578937e-17+1.08402503e-17j,
        1.28578937e-17-1.08402503e-17j])

array([[ 4.16025147e-01+0.00000000e+00j,  5.00000000e-01+0.00000000e+00j,
         2.23606798e-01+0.00000000e+00j, -2.13720803e-02-2.22640967e-01j,
        -2.13720803e-02+2.22640967e-01j],
       [ 4.16025147e-01+0.00000000e+00j, -5.00000000e-01+0.00000000e+00j,
         2.23606798e-01+0.00000000e+00j, -6.70801188e-01+4.35328926e-17j,
        -6.70801188e-01-4.35328926e-17j],
       [ 4.16025147e-01+0.00000000e+00j,  5.00000000e-01+0.00000000e+00j,
         2.23606798e-01+0.00000000e+00j,  2.13720803e-02+2.22640967e-01j,
         2.13720803e-02-2.22640967e-01j],
       [ 4.16025147e-01+0.00000000e+00j, -5.00000000e-01+0.00000000e+00j,
         2.23606798e-01+0.00000000e+00j,  6.70801188e-01+0.00000000e+00j,
         6.70801188e-01-0.00000000e+00j],
       [ 5.54700196e-01+0.00000000e+00j,  1.37920956e-16+0.00000000e+00j,
        -8.94427191e-01+0.00000000e+00j,  1.65968556e-17-1.06442656e-17j,
         1.65968556e-17+1.06442656e-17j]])

In [24]:
v = np.real(V[:,0])/np.sum(np.real(V[:,0]))
display(v)

array([0.1875, 0.1875, 0.1875, 0.1875, 0.25  ])

In [25]:
# Dimostriamo che la catena è regolare
# Calcoliamo P^2
display(np.dot(P,P))

array([[0.30555556, 0.08333333, 0.30555556, 0.08333333, 0.22222222],
       [0.08333333, 0.30555556, 0.08333333, 0.30555556, 0.22222222],
       [0.30555556, 0.08333333, 0.30555556, 0.08333333, 0.22222222],
       [0.08333333, 0.30555556, 0.08333333, 0.30555556, 0.22222222],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.33333333]])

In [26]:
# Tutti gli elementi sono positivi, quindi la definizione è soddisfatta.

In [27]:
# Metodo Monte Carlo

In [28]:
n = 5 # Dimensione della matrice
F = np.zeros(n)
j = np.random.randint(n)
N = 100000
for i in range(N):
    j_multi = np.random.multinomial(1, P[j,:])
    j = np.nonzero(j_multi)[0][0]
    F[j] = F[j]+1
vv = F/N
display(vv)

array([0.18639, 0.18686, 0.1881 , 0.18726, 0.25139])