# Esercizio 1

In una strada di montagna si ha durante il giorno un traffico molto ridotto, con il passaggio mediamente di 3 auto l'ora, che segue una distribuzione poissiana con lambda_a = 3

1. Qual è la probabilità che in un'ora non passi nessuna auto?
2. Qual è la probabilità che passino in un'ora più di 3 auto?

Sulla stessa strada transitano anche bicilette, secondo una analoga distribuzione di Poisson avente lambda_b = 4

3. Qual è la probabilità che in un'ora passino solo auto (cioè nessuna bicicletta e almeno un'auto)?
4. Qual è la probabilità che passino in un'ora 8 veicoli (in totale tra auto e bici)?

In [17]:
from scipy.stats import poisson

lambda_a = 3
lambda_b = 4

quesito1 = poisson.pmf(0, lambda_a)
print("Probabilità che in un'ora non passi nessuna auto: ", quesito1)

quesito2 = 1 - poisson.cdf(3, lambda_a)
print("Probabilità che passino in un'ora più di 3 auto: ", quesito2)

nessunaBici = poisson.pmf(0, lambda_b)
almenoUnAuto = 1 - poisson.pmf(0, lambda_a)
quesito3 = nessunaBici * almenoUnAuto
print("Probabilità che in un'ora passino solo auto: ", quesito3)

# 4. Probabilità che passino in un'ora 8 veicoli (totale tra auto e bici)
quesito4 = poisson.pmf(8, lambda_a + lambda_b)
print(f"Probabilità che passino in un'ora 8 veicoli: ", quesito4)

Probabilità che in un'ora non passi nessuna auto:  0.049787068367863944
Probabilità che passino in un'ora più di 3 auto:  0.35276811121776874
Probabilità che in un'ora passino solo auto:  0.017403756923179664
Probabilità che passino in un'ora 8 veicoli:  0.1303774322150455


# Esercizio 2

Una compagnia aerea ha stimato il peso medio del bagaglio a mano dei propri passeggeri sia m = 5.5kg. Viene effettuata una misurazione su un campione di 100 passeggeri ottenendo un peso medio dei babgagli di mu = 5.7kg con una varianza camionaria di 1.5kg.

1. Si può ritenere che il peso medio reale sia maggiore di m con una confidenza del 95%
2. Si calcoli il p-value del test precedente

In [18]:
import numpy as np
from scipy.stats import norm

m = 5.5
n = 100
mu = 5.7
var = 1.5

alpha = 0.05
# Test unilatero a destra

Z0 = ((mu - m) / np.sqrt(var)) * np.sqrt(n)
phi = norm.ppf(1-alpha)

print("Z0: ", Z0, "phi: ", phi)

if (Z0 > phi):
    print("Si rigetta l'ipotesi nulla")
else:
    print("Non è possibile rigettare l'ipotesi nulla")

p_value = 1-norm.cdf(Z0)
print("p_value: ", p_value)

Z0:  1.6329931618554536 phi:  1.6448536269514722
Non è possibile rigettare l'ipotesi nulla
p_value:  0.05123521742987458


# Esercizio 3

Sia dato un grafo E di vertici V con i = 1,2,3,4, su cui si realizza una passeggiata aleatoria in cui sono possibili le transizioni: da V1 a V2 V3, da V2 a V3 V4, da V3 a V2 V4 e da V4 a V1 V2, tutte con uguale probabilità p=1/2

1. Scrivere la matrice di transizione del processo, e verificare che la corrispondente catena di Markov sia regolare.
2. Trovare sia analiticamente che attraverso un metodo Monte Carlo lo stato stazionario del processo.


In [19]:
import numpy as np

P = np.array([[0,   1/2, 1/2, 0],   
              [0,   0,   1/2, 1/2], 
              [1/2, 0,   0,   1/2], 
              [1/2, 1/2, 0,   0]])  

P_squared = np.dot(P, P)
print(P_squared)

print("La catena di Markov è regolare perché tutti i valori di P^2 sono positivi")

# Metodo analiticp

lam, V = np.linalg.eig(P.T)  
v = np.real(V[:, 0]) / np.sum(np.real(V[:, 0]))  
print(v)

# Metodo Monte Carlo
 
n=4
F=np.zeros(n)
j=np.random.randint(n)
F[j]=1
N=100000

for i in range(N):
    j_multi=np.random.multinomial(1,P[j,:])
    j=np.nonzero(j_multi)[0][0]
    F[j]=F[j]+1
 
vv=F/N
print(vv)

[[0.25 0.   0.25 0.5 ]
 [0.5  0.25 0.   0.25]
 [0.25 0.5  0.25 0.  ]
 [0.   0.25 0.5  0.25]]
La catena di Markov è regolare perché tutti i valori di P^2 sono positivi
[0.25 0.25 0.25 0.25]
[0.24976 0.25037 0.24972 0.25016]
