# Esercizio 1

Le specifiche tecniche per la velocità di combustione di un propellente richiedono che essa sia di 50 cm/s. Sappiamo che la deviazione standard è di 2 cm/s. Si effettuano 24 misurazioni: 51.0, 50.2, 49.5, 48.7, 50.2, 50.5, 49.6, 51.1, 50.6, 49.1, 53.1, 50.4, 49.3, 48.9, 50.3, 51.8, 51.3, 48.5, 49.3, 55.1, 53.1, 52.5, 55.1, 50.6.

Si può rigettare l'ipotesi nulla con un livello di significatività del 5%? E se invece si richiedesse l'1%? Calcolare infine il p-value.

Supponiamo che lo sperimentatore voglia impostare il test in modo che la reale velocità di combustione media differisca da 50 cm/s per al più 1 cm/s. Si vuole inoltre che il test affermerà questo fatto (cioè rigetterà H0 : µ = 50) con una probabilità del 90% e un livello di significatività del 5%. Determinare la dimensione campionaria.


In [91]:
import numpy as np
from scipy.stats import norm

X = np.array(
    [
        51.0,
        50.2,
        49.5,
        48.7,
        50.2,
        50.5,
        49.6,
        51.1,
        50.6,
        49.1,
        53.1,
        50.4,
        49.3,
        48.9,
        50.3,
        51.8,
        51.3,
        48.5,
        49.3,
        55.1,
        53.1,
        52.5,
        55.1,
        50.6,
    ]
)
n = X.size

sigma = 2
mu_0 = 50

media = np.mean(X)

Z_0 = (media - mu_0) / sigma * np.sqrt(n)

# Test con livello di significatività del 5%

alpha = 0.05
PHI = norm.ppf(1 - alpha / 2)

print("Z0: ", Z_0)
print("PHI: ", PHI)

print("Z0 > PHI: Si rigetta l'ipotesi nulla")

Z0:  2.020829037796111
PHI:  1.959963984540054
Z0 > PHI: Si rigetta l'ipotesi nulla


In [92]:
# Test con livello di significatività del 1%

alpha = 0.01
PHI = norm.ppf(1 - alpha / 2)

print("Z0: ", Z_0)
print("PHI: ", PHI)

print("Z0 < PHI: Non abbiamo elementi sufficienti per rigettare l'ipotesi nulla")

Z0:  2.020829037796111
PHI:  2.5758293035489004
Z0 < PHI: Non abbiamo elementi sufficienti per rigettare l'ipotesi nulla


In [93]:
# Calcolo del p-value

p_value = 2 * (1 - norm.cdf(np.abs(Z_0)))
print("p-value: ", p_value)

p-value:  0.04329746577930438


In [94]:
# Determiniamo la dimensione campionaria

alpha = 0.05
beta = 0.1
delta = 1

PHI = norm.ppf(1.0 - alpha / 2)
print(-PHI - delta * np.sqrt(n) / sigma, "< -3")

dimensione_campionaria = (PHI + norm.ppf(1 - beta)) ** 2 * sigma**2 / delta**2

print("Dimensione campionaria: ", dimensione_campionaria)

-4.409453727323232 < -3
Dimensione campionaria:  42.029692245762476


# Esercizio 2

Si vuole testare ad un livello di significatività α = 0.05 se il carico di rottura di un materiale supera 10 MPa, tenendo presente che 22 prove hanno fornito i seguenti risultati

19.8 18.5 17.6 16.7 15.8
15.4 14.1 13.6 11.9 11.4
11.4 8.8 7.5 15.4 15.4
19.5 14.9 12.7 11.9 11.4
10.1 7.9

Calcolare inoltre il p-value.


In [95]:
import numpy as np
from scipy.stats import t

X = np.array(
    [
        19.8,
        18.5,
        17.6,
        16.7,
        15.8,
        15.4,
        14.1,
        13.6,
        11.9,
        11.4,
        11.4,
        8.8,
        7.5,
        15.4,
        15.4,
        19.5,
        14.9,
        12.7,
        11.9,
        11.4,
        10.1,
        7.9,
    ]
)
n = X.size

media = np.mean(X)
S = np.std(X, ddof=1)
mu_0 = 10

T_0 = (media - mu_0) / S * np.sqrt(n)

alpha = 0.05
t = t.ppf(1 - alpha, n - 1)

print("T0: ", T_0)
print("t: ", t)

print("T0 > T: Si può rigettare l'ipotesi")

T0:  4.901682101212391
t:  1.7207429028118775
T0 > T: Si può rigettare l'ipotesi


In [96]:
# Calcolo del p-value
from scipy.stats import t



p_value = 1 - t.cdf(T_0, n - 1)
print("p-value: ", p_value)

p-value:  3.781272593450513e-05


# Esercizio 3

Un macchinario riempie automaticamente delle bottiglie. Da un campione di 20 misurazioni si ottengono i seguenti valori (in litri)

2.05, 2.04, 1.98, 1.96, 2.03, 2.01, 1.97, 1.99, 2.01, 2.05
1.96, 1.95, 2.04, 2.01, 1.97, 1.96, 2.02, 2.04, 1.98, 1.94

Se la deviazione standard fosse superiore a 0.05 litri, la proporzione di bottiglie sotto o sovrariempite sarebbe non accettabile.

I dati del campione contengono prove che suggeriscono che il produttore abbia un problema con le bottiglie riempite troppo o troppo poco? Utilizzare α = 0.05 e assumere che il volume di riempimento abbia una distribuzione normale.


In [97]:
import numpy as np
from scipy.stats import chi2

# Test unilatero a sinistra

X = np.array(
    [
        2.05,
        2.04,
        1.98,
        1.96,
        2.03,
        2.01,
        1.97,
        1.99,
        2.01,
        2.05,
        1.96,
        1.95,
        2.04,
        2.01,
        1.97,
        1.96,
        2.02,
        2.04,
        1.98,
        1.94,
    ]
)
n = X.size

sig0 = 0.05
S = np.std(X, ddof=1)

W0 = S**2 / sig0**2 * (n - 1)

alpha = 0.05
CHI = chi2.ppf(alpha, n - 1)

print("W0: ", W0)
print("CHI: ", CHI)

print("W0 < CHI: Si può rigettare l'ipotesi")

W0:  9.967999999999988
CHI:  10.117013063859044
W0 < CHI: Si può rigettare l'ipotesi


# Esercizio 4

In una catena di produzione si vuole mantenere il numero di pezzi difettosi al di sotto del 5%.

Si analizza un campione di 200 pezzi e si trovano 4 pezzi difettosi.
Si può asserire ad un livello di significativit`a α = 0.05 che la produzione rispetta le aspettative?

Supponendo che il valore vero sia p∗ = 0.03 e supponendo che il costruttore voglia
accettare un valore dell’errore di secondo tipo β = 0.1, quale ampiezza dovrebbe avere il campione?


In [98]:
import numpy as np
from scipy.stats import norm

# Test unilatero a sinistra

p0 = 0.05
n = 200
p = 4 / n

Z_0 = (p - p0) / (np.sqrt(p0 * (1 - p0))) * np.sqrt(n)

alpha = 0.05
PHI = norm.ppf(alpha)

print("Z0: ", Z_0)
print("PHI: ", PHI)

print("Z0 < PHI: Si può rigettare l'ipotesi")

Z0:  -1.946657053569151
PHI:  -1.6448536269514729
Z0 < PHI: Si può rigettare l'ipotesi


In [99]:
p_star = 0.03
beta = 0.1

dimensione_campionaria = (
    (norm.ppf(beta) * np.sqrt(p_star * (1.0 - p_star)) + PHI * np.sqrt(p0 * (1.0 - p0)))
    / (p0 - p_star)
) ** 2.0
print("Dimensione campionaria: ", dimensione_campionaria)

Dimensione campionaria:  832.6221546780524


Si desidera confrontare due tipi di preparati per pittura, presumendo che abbiano tempi di essiccamento diversi. Si ipotizza che la deviazione standard del tempo di essiccamento per ciascun tipo di preparato sia di 8 minuti. Sono state tinteggiate 10 pareti con il trattamento 1 e altrettante con il trattamento 2. Le medie campionarie rilevate sono X¯ = 121 minuti e Y¯ = 112 minuti. Si intende stabilire se il tempo di essiccamento del campione 1 sia maggiore di quello del campione 2, con un livello di significatività α = 0.05.

Inoltre, si procede al calcolo dell'intervallo di confidenza per la differenza dei tempi medi di essiccamento.


In [100]:
import numpy as np
from scipy.stats import norm

# Test unilatero a destra

X_1 = 121
X_2 = 112
n1 = n2 = 10
sig1 = sig2 = 8
alpha = 0.05

Z_0 = (X_1 - X_2) / np.sqrt(sig1**2 / n1 + sig2**2 / n2)
PHI = norm.ppf(1 - alpha)

print("Z0: ", Z_0)
print("PHI: ", PHI)

print("Z0 > PHI: Si può rigettare l'ipotesi")

Z0:  2.5155764746872635
PHI:  1.6448536269514722
Z0 > PHI: Si può rigettare l'ipotesi


In [101]:
# Intervallo di confidenza per la differenza dei tempi medi di essiccamento

intervallo = X_1 - X_2 - PHI * np.sqrt(sig1**2 / n1 + sig2**2 / n2)
print("Intervallo di confidenza: ", intervallo)

Intervallo di confidenza:  3.115192763359085


Quindici adulti, con età compresa tra 35 e 50 anni, hanno partecipato a uno studio per valutare gli effetti di dieta alimentare ed esercizio fisico sul livello di colesterolo nel sangue. In ciascun individuo, il livello di colesterolo è stato misurato inizialmente e tre mesi dopo l'adozione della dieta e dell'allenamento. Con un livello di significatività α = 0.05, si desidera stabilire se la dieta ed esercizio fisico portino effettivamente a una riduzione del livello medio di colesterolo.

![Immagine](img/test.png)


In [102]:
import numpy as np
from scipy.stats import t

# Test unilatero a destra

X = np.array(
    [
        [
            265.0,
            240.0,
            258.0,
            295.0,
            251.0,
            245.0,
            287.0,
            314.0,
            260.0,
            279.0,
            283.0,
            240.0,
            238.0,
            225.0,
            247.0,
        ],
        [
            229.0,
            231.0,
            227.0,
            240.0,
            238.0,
            241.0,
            234.0,
            256.0,
            247.0,
            239.0,
            246.0,
            218.0,
            219.0,
            226.0,
            233.0,
        ],
    ]
)

D = X[0, :] - X[1, :]
n = D.size

D_bar = np.mean(D)
S = np.std(D, ddof=1)

T_0 = D_bar / S * np.sqrt(n)

alpha = 0.05
t = t.ppf(1 - alpha, n - 1)

print("T0: ", T_0)
print("T: ", t)

print("T0 > T: Si può rigettare l'ipotesi")

T0:  5.4658739941050065
T:  1.7613101357748562
T0 > T: Si può rigettare l'ipotesi


Si vuole testare se un dado sia equilibrato o meno ad un livello di significatività α = 0.05.
Si effettuano 100 lanci, registrando i risultati riportati nella seguente tabella.

![Immagine](img/tabella1.png)

Dopo aver aumentato la dimensione campionaria, si registrano i risultati riportati nella seguente
tabella. Si ripeta il test di cui sopra con i nuovi dati.

![Immagine](img/tabella2.png)

Si ripeta quest’ultimo test con α = 0.01.


In [103]:
import numpy as np
from scipy.stats import chi2

X = np.array([20.0, 7.0, 12.0, 18.0, 20.0, 23.0])
N = np.sum(X)
p = 1 / 6

E = np.ones(6) * p * N

T = np.sum((X - E) ** 2.0 / E)

alpha = 0.05
CHI = chi2.ppf(1.0 - alpha, 6 - 1)

print("T: ", T)
print("CHI: ", CHI)

print("T < CHI: NON è possibile rigettare l'ipotesi")

T:  10.760000000000002
CHI:  11.070497693516351
T < CHI: NON è possibile rigettare l'ipotesi


In [104]:
Y = np.array([388.0, 322.0, 314.0, 316.0, 344.0, 316.0])
N = np.sum(Y)
p = 1 / 6

E = np.ones(6) * p * N
T = np.sum((Y - E) ** 2.0 / E)

print("T: ", T)
print("CHI: ", CHI)

print("T > CHI: Si può rigettare l'ipotesi")

T:  12.616000000000001
CHI:  11.070497693516351
T > CHI: Si può rigettare l'ipotesi


Si può adattare una distribuzione di Poisson ai dati della seguente tabella?

![Immagine](img/poisson.png)


In [105]:
import numpy as np
from scipy.stats import chi2
from scipy.stats import poisson

X = np.array([584.0, 398.0, 165.0, 35.0, 15.0])
m = X.size
N = np.sum(X)

p = X / N
X_n = X * np.array([0, 1, 2, 3, 4])
lam = sum(X_n) / N

p0 = np.zeros(5)
for i in range(4):
    p0[i] = poisson.pmf(i, lam)
p0[4] = 1.0 - np.sum(p0)

T = N * np.sum((p - p0) ** 2.0 / p0)
print("T: ", T)

alpha = 0.05
CHI = chi2.ppf(1.0 - alpha, m - 1 - 1)
print("CHI: ", CHI)

T:  7.6054880723053175
CHI:  7.814727903251179


Si vuole testare se un antibiotico è efficace. Si considerano 170 pazienti. I dati ottenuti sono stati raccolti nella tabella seguente, detta tabella di contingenza

![Immagine](img/tabella3.png)

I due effetti, trattamento e guarigione, sono indipendenti? Si usi α = 0.05


In [106]:
import numpy as np
from scipy.stats import chi2

X = np.array([[44., 10.],[81., 35]])
n = 170

p = np.array([54., 116.])/n
q = np.array([125., 45.])/n

# Probabilità congiunta empirica
pi = X/n

T = 0

for h in range(2):
    for k in range(2):
        T = T + (p[h]*q[k]-pi[h][k])**2./pi[h][k]
T = n*T

alpha = 0.05
CHI = chi2.ppf(1.-alpha,(2-1)*(2-1))

print("T: ", T)
print("CHI: ", CHI)

print("T < CHI: NON è possibile rigettare l'ipotesi")

T:  3.0175117739708286
CHI:  3.841458820694124
T < CHI: NON è possibile rigettare l'ipotesi


# Esercizio
Un motore a reazione è formato legando insieme un propellente di accensione e un propellente
di sostegno all’interno di un alloggiamento metallico. La resistenza al taglio del legame tra i
due tipi di propellente è una caratteristica importante.
Vogliamo testare l’ipotesi che la mediana della resistenza al taglio sia 2000 psi con una significatività α = 0.05.
I dati sono riportati nel file Dataset motore.dat.

In [107]:
#test bilatero
import numpy as np
from scipy.stats import binom

In [108]:
alpha=0.05
mediana_0 = 2000

In [109]:
X = np.loadtxt('Dataset_motore.dat')
display(X)
n=X.size

array([2158.7 , 1678.15, 2316.  , 2061.3 , 2207.5 , 1708.3 , 1784.7 ,
       2575.1 , 2357.9 , 2256.7 , 2165.2 , 2399.55, 1779.8 , 2336.75,
       1765.3 , 2053.5 , 2414.4 , 2200.5 , 2654.2 , 1753.7 ])

In [110]:
#Calcoliamo le differenze
D=X-mediana_0
print(D)

[ 158.7  -321.85  316.     61.3   207.5  -291.7  -215.3   575.1   357.9
  256.7   165.2   399.55 -220.2   336.75 -234.7    53.5   414.4   200.5
  654.2  -246.3 ]


In [111]:
r_piu = D>0 #Diventa un array di bool -> true se la condizione (D>0) è vera 
r_piu = r_piu.astype(int) #Conversione in int (quindi diventeranno tutti 0 o 1)
r_piu = np.sum(r_piu) #somma dei valori >0

In [113]:
print("r+: ", r_piu)
print("n/2: ", n/2)
print("r+ > n/2")
k=range(r_piu,n+1)
Y=binom.pmf(k,n,0.5)
p_value=2*(np.sum(Y))

print("p_value ",p_value)
# Poiché il p-value è maggiore della soglia fissata alpha = 0.05
# Non abbiamo elementi sufficienti per rigettare H0

r+:  14
n/2:  10.0
r+ > n/2
p_value  0.11531829833984363


# Esercizio
In un esperimento si confrontano quattro diverse tecniche di mescolamento per il cemento e
si misura la resistenza alla trazione. Si può affermare che la tecnica di mescolamento influisca
sulla resistenza alla trazione? Si usi α = 0.05.

![tabella](img/tabella4.png)

In [114]:
import numpy as np

In [115]:
X_1 = np.array([3129., 3000., 2865., 2890.])
X_2 = np.array([3200., 3000., 2975., 3150.])
X_3 = np.array([2800., 2900., 2985., 3050.])
X_4 = np.array([2600., 2700., 2600., 2765.])

In [117]:
alpha = 0.05
n = np.array([X_1.size, X_2.size, X_3.size, X_4.size])
m = 4

In [118]:
N = np.sum(n)
Y = np.concatenate([X_1, X_2, X_3, X_4])

In [119]:
from scipy.stats import rankdata
R = rankdata(Y)
display(R)

array([14. , 11.5,  6. ,  7. , 16. , 11.5,  9. , 15. ,  5. ,  8. , 10. ,
       13. ,  1.5,  3. ,  1.5,  4. ])

In [120]:
S2 = (np.sum(R**2.)-N*(N+1)**2./4.) / (N-1)
display(S2)

22.6

In [121]:
RR = np.zeros(m)
for i in range(m):
    RR[i] = np.sum(R[m*i:m*(i+1)])
display(RR)

array([38.5, 51.5, 36. , 10. ])

In [122]:
H = (np.sum(RR**2. / n)-N*(N+1)**2./4.)/S2
display(H)

10.027654867256636

In [123]:
from scipy.stats import chi2
alpha = 0.05
CHI = chi2.ppf(alpha, m-1)
display(CHI)

0.35184631774927144

In [124]:
# Si rigetta H0 in favore di H1