# Esercizio 1

Data la matrice di transizione

0 1/4 3/4

0 1/2 1/2

3/4 0 1/4

dimostrare che ha un’unica distribuzione stazionaria π e determinarla sia analiticamente che con
il metodo Monte Carlo confrontando infine i risultati.


In [44]:
import numpy as np

# Metodo Analitico

P = np.array([[0, 1 / 4, 3 / 4], [0, 1 / 2, 1 / 2], [3 / 4, 0, 1 / 4]])
P2 = np.dot(P, P)

lam, V = np.linalg.eig(P.T)
v = V[:, 1] / np.sum(V[:, 1])

print(v)

[0.35294118 0.17647059 0.47058824]


In [45]:
# Metodo Monte Carlo

n = 3
F = np.zeros(n)
j = np.random.randint(n)
F[j] = 1

N = 100000

for i in range(N):
    j_multi = np.random.multinomial(1, P[j, :])
    j = np.nonzero(j_multi)[0][0]
    F[j] = F[j] + 1
vv = F / N

print(vv)

[0.35376 0.17395 0.4723 ]


# Esercizio 2

Consideriamo la passeggiata aleatoria sul grafo della figura seguente.

![Grafo](img/grafo.png)

Determinare la matrice di transizione della catena di Markov associata, dimostrare che la catena
è regolare e determinare la distribuzione invariante sia analiticamente che con il metodo Monte
Carlo.


In [46]:
import numpy as np

# Calcolo della matrice di transizione

P = np.array(
    [
        [0, 1 / 3, 0, 1 / 3, 1 / 3],
        [1 / 3, 0, 1 / 3, 0, 1 / 3],
        [0, 1 / 3, 0, 1 / 3, 1 / 3],
        [1 / 3, 0, 1 / 3, 0, 1 / 3],
        [1 / 4, 1 / 4, 1 / 4, 1 / 4, 0],
    ]
)

print(P)

[[0.         0.33333333 0.         0.33333333 0.33333333]
 [0.33333333 0.         0.33333333 0.         0.33333333]
 [0.         0.33333333 0.         0.33333333 0.33333333]
 [0.33333333 0.         0.33333333 0.         0.33333333]
 [0.25       0.25       0.25       0.25       0.        ]]


In [47]:
# Metodo analitico

lam, V = np.linalg.eig(P.T)
v = np.real(V[:, 0]) / np.sum(np.real(V[:, 0]))

print(v)

[0.1875 0.1875 0.1875 0.1875 0.25  ]


In [48]:
# Dimostriamo che la catena è regolare
print(np.dot(P, P))
# Tutti gli elementi sono positivi, quindi la definizione è soddisfatta.

[[0.30555556 0.08333333 0.30555556 0.08333333 0.22222222]
 [0.08333333 0.30555556 0.08333333 0.30555556 0.22222222]
 [0.30555556 0.08333333 0.30555556 0.08333333 0.22222222]
 [0.08333333 0.30555556 0.08333333 0.30555556 0.22222222]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.33333333]]


In [49]:
n = 5
F = np.zeros(n)
j = np.random.randint(n)
F[j] = 1
N = 100000

for i in range(N):
    j_multi = np.random.multinomial(1, P[j, :])
    j = np.nonzero(j_multi)[0][0]
    F[j] = F[j] + 1

vv = F / N

print(v)

[0.1875 0.1875 0.1875 0.1875 0.25  ]
