In [2]:
# Test di Kruskal-Wallis
# Ipotesi nulla: Il mescolamento non influisce sulla resistenza alla trazione (mu_1=mu_2=mu_3=mu_4)
# Ipotesi alternativa: Il mescolamento influisce sulla resistenza alla trazione

In [3]:
import numpy as np

In [11]:
X_1 = np.array([3129., 3000., 2865., 2890.])
X_2 = np.array([3200., 3000., 2975., 3150.])
X_3 = np.array([2800., 2900., 2985., 3050.])
X_4 = np.array([2600., 2700., 2600., 2765.])

In [48]:
m = 4
n = np.array([X_1.size, X_2.size, X_3.size, X_4.size])
display(n)

array([4, 4, 4, 4])

In [49]:
N = np.sum(n)
display(N)

16

In [50]:
Y = np.concatenate([X_1, X_2, X_3, X_4])
display(Y)

array([3129., 3000., 2865., 2890., 3200., 3000., 2975., 3150., 2800.,
       2900., 2985., 3050., 2600., 2700., 2600., 2765.])

In [55]:
from scipy.stats import rankdata
R = rankdata(Y)
display(R)

array([14. , 11.5,  6. ,  7. , 16. , 11.5,  9. , 15. ,  5. ,  8. , 10. ,
       13. ,  1.5,  3. ,  1.5,  4. ])

In [59]:
S2 = (np.sum(R**2.)-N*(N+1)**2./4.) / (N-1)
display(S2)

22.6

In [61]:
RR = np.zeros(m)
for i in range(m):
    RR[i] = np.sum(R[m*i:m*(i+1)])
display(RR)

array([38.5, 51.5, 36. , 10. ])

In [68]:
H = (np.sum(RR**2. / n)-N*(N+1)**2./4.)/S2
display(H)

10.027654867256636

In [69]:
from scipy.stats import chi2
alpha = 0.05
CHI = chi2.ppf(alpha, m-1)
display(CHI)

0.35184631774927144

In [ ]:
# Si rigetta H0 in favore di H1