In [1]:
# Determinare la distribuzione stazionaria della matrice assegnata

In [2]:
# 1->2, 1->3
# 2->2, 2->3
# 3->1, 3->3
# 1->2->3->1 (per la proprietà transitiva)
# Tutti gli stati comunicano tra loro, quindi la catena è irriducibile.
# Inoltre p_22>0, p_33>0 e quindi per il criterio di regolarità essa è regolare.
# Per il Teorema di Markov la catena ha un'unica distribuzione stazionaria.
#
# D'altra parte la catena è irriducibile e l'insieme degli stati è finito.
# Quindi esiste un'unica distribuzione stazionaria.

In [3]:
import numpy as np

In [4]:
P = np.array([[0, 1/4, 3/4],[0, 1/2, 1/2],[3/4, 0, 1/4]])
display(P)

array([[0.  , 0.25, 0.75],
       [0.  , 0.5 , 0.5 ],
       [0.75, 0.  , 0.25]])

In [6]:
# Calcoliamo P^2
display(np.dot(P,P))

array([[0.5625, 0.125 , 0.3125],
       [0.375 , 0.25  , 0.375 ],
       [0.1875, 0.1875, 0.625 ]])

In [7]:
# Osserviamo che P^2 ha tutti gli elementi strettamente positivi e quindi P è regolare per definizione

In [8]:
# Metodo analitico

In [9]:
lam, V = np.linalg.eig(P.T)
display(lam)
display(V)

array([-0.57569391,  1.        ,  0.32569391])

array([[ 0.78010553, -0.57469577,  0.55506939],
       [-0.18130286, -0.28734789, -0.79611302],
       [-0.59880267, -0.76626103,  0.24104363]])

In [11]:
v = V[:,1]/np.sum(V[:,1])
display(v)

array([0.35294118, 0.17647059, 0.47058824])

In [13]:
# Metodo Monte Carlo

In [29]:
n = 3 # Dimensione della matrice
F = np.zeros(n)
j = np.random.randint(n)
F[j] = 1
N = 1000000
for i in range(N):
    j_multi = np.random.multinomial(1, P[j,:])
    j = np.nonzero(j_multi)[0][0]
    F[j] = F[j]+1
vv = F/N
display(vv)

array([0.353091, 0.175981, 0.470929])